### PR TITLE
Bugfix for Inc-5312

### PR DESCRIPTION
**Pull request by laudena**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (if relevant)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix
- [x] Refactoring

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**If this is a UI change / fix, please also add a screenshot**

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I added the relevant people as reviewers to my PR

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks @laudena, I'll review the changes right away!

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Make sure all checks pass, only then you can merge the PR.

**Comment by laudena** [comment]
Isn't that the preview page? seems like the image is there. What am I missing?

Screen Shot 2022-04-21 at 11 29 04 pm

**Review by vanessa-cooper — APPROVED** [review]
Excellent job @laudena! You're now able to merge the PR.

**Pull request merged**
