### PR TITLE
Deployment frontend

### PR DESCRIPTION
**Pull request by laudena**
# Description

Added support for backend url in the environment variables. allows deployment to heroku, for instance

Fixes # (if relevant)

## Type of change

Please delete options that are not relevant.

- [/] A documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**If this is a UI change / fix, please also add a screenshot**

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I added the relevant people as reviewers to my PR

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Nice! Let me review the code for a second.

**Review by vanessa-cooper — DISMISSED** [review]
Um… something’s missing. Are you sure you’ve added the right config var to your Heroku config?

**Comment by laudena** [comment]
Screen Shot 2022-04-23 at 6 17 54 pm

**Review by vanessa-cooper — APPROVED** [review]
Done! The frontend is now connected to the correct backend. Don’t forget to merge the PR.

**Pull request merged**
